# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRegisterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField(null=True)),
                ('indexing_file', models.FileField(upload_to='register_files/')),
                ('state', models.CharField(choices=[('UPLOADED', 'Cargado'), ('PROCESSING', 'Procesando'), ('PROCESSED', 'Procesado'), ('FAILED', 'Error')], max_length=20)),
                ('logs', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(max_length=100, unique=True)),
                ('catalog_url', models.URLField()),
                ('indexable', models.BooleanField()),
                ('catalog', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='ReadDataJsonTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Procesando cat\xe1logos'), ('INDEXING', 'Indexando series'), ('FINISHED', 'Finalizada'), ('ERROR', 'Error')], max_length=20)),
                ('created', models.DateTimeField()),
                ('finished', models.DateTimeField(null=True)),
                ('logs', models.TextField(default='-')),
                ('stats', models.TextField(default='{}')),
                ('catalogs', models.ManyToManyField(blank=True, to='management.Node')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetIndexingFile',
            fields=[
                ('baseregisterfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.BaseRegisterFile')),
            ],
            bases=('management.baseregisterfile',),
        ),
        migrations.CreateModel(
            name='NodeRegisterFile',
            fields=[
                ('baseregisterfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.BaseRegisterFile')),
            ],
            bases=('management.baseregisterfile',),
        ),
        migrations.AddField(
            model_name='baseregisterfile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
