# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20180323_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexingTaskCron',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='node',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='task',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
    ]
