# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', 'ensure_upkeep_job_exists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synchronizer',
            name='cron_string',
        ),
        migrations.AddField(
            model_name='synchronizer',
            name='frequency',
            field=models.CharField(choices=[('every day', 'every day'), ('week days', 'week days')], default='every day', max_length=16),
        ),
        migrations.AddField(
            model_name='synchronizer',
            name='scheduled_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
