# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_datajsonar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRegisterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField(null=True)),
                ('indexing_file', models.FileField(upload_to='register_files/')),
                ('state', models.CharField(choices=[('UPLOADED', 'Cargado'), ('PROCESSING', 'Procesando'), ('PROCESSED', 'Procesado'), ('FAILED', 'Error')], max_length=20)),
                ('logs', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200, unique=True)),
                ('metadata', models.TextField()),
                ('updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
                ('metadata', models.TextField()),
                ('indexable', models.BooleanField(default=False)),
                ('present', models.BooleanField(default=True)),
                ('updated', models.BooleanField(default=False)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('metadata', models.TextField()),
                ('download_url', models.URLField(max_length=1024)),
                ('updated', models.BooleanField(default=False)),
                ('data_file', models.FileField(blank=True, max_length=2000, upload_to=django_datajsonar.models.filepath)),
                ('data_hash', models.CharField(default='', max_length=128)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('indexable', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('identifier', models.CharField(max_length=200, null=True)),
                ('metadata', models.TextField()),
                ('updated', models.BooleanField(default=False)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Distribution')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(max_length=100, unique=True)),
                ('catalog_url', models.URLField()),
                ('indexable', models.BooleanField()),
                ('catalog', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='ReadDataJsonTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Procesando catálogos'), ('INDEXING', 'Indexando series'), ('FINISHED', 'Finalizada'), ('ERROR', 'Error')], max_length=20)),
                ('created', models.DateTimeField()),
                ('finished', models.DateTimeField(null=True)),
                ('logs', models.TextField(default='-')),
                ('stats', models.TextField(default='{}')),
                ('catalogs', models.ManyToManyField(blank=True, to='django_datajsonar.Node')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetIndexingFile',
            fields=[
                ('baseregisterfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_datajsonar.BaseRegisterFile')),
            ],
            bases=('django_datajsonar.baseregisterfile',),
        ),
        migrations.CreateModel(
            name='NodeRegisterFile',
            fields=[
                ('baseregisterfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_datajsonar.BaseRegisterFile')),
            ],
            bases=('django_datajsonar.baseregisterfile',),
        ),
        migrations.AddField(
            model_name='baseregisterfile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
