# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='indexable',
        ),
        migrations.AddField(
            model_name='catalog',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalog',
            name='present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distribution',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distribution',
            name='present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='field',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='present',
            field=models.BooleanField(default=True),
        ),
    ]
