# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0002_auto_20180507_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='title',
            field=models.CharField(default='Title pending', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
