# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0003_auto_20190301_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'Additional metadata', 'verbose_name_plural': 'Additional metadata'},
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='indexable',
            new_name='federable',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='indexable',
            new_name='federable',
        ),
    ]
