# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0003_auto_20190301_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'Additional metadata', 'verbose_name_plural': 'Additional metadata'},
        ),
        migrations.AlterField(
            model_name='dataset',
            name='indexable',
            field=models.BooleanField(default=False, verbose_name='federable'),
        ),
        migrations.AlterField(
            model_name='node',
            name='indexable',
            field=models.BooleanField(verbose_name='federable'),
        ),
    ]
