# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0004_auto_20180510_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdatajsontask',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Procesando catálogos'), ('FINISHED', 'Finalizada'), ('ERROR', 'Error'), ('INDEXING', 'Indexando series')], max_length=20),
        ),
    ]
