# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0004_auto_20180510_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='download_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
