# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0005_readdatajsontask_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizer',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Node'),
        ),
    ]
