# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-07 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0006_synchronizer_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='catalog_label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='types',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='datosgobar_url',
            new_name='url_datosgobar',
        ),
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='homepage_url',
            new_name='url_homepage',
        ),
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='json_url',
            new_name='url_json',
        ),
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='xlsx_url',
            new_name='url_xlsx',
        ),
        migrations.RemoveField(
            model_name='nodemetadata',
            name='argentinagobar_id',
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='argentinagobar_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
