# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-14 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_argentinagobar_ids(apps, _schema_editor):
    Jurisdiction = apps.get_model('django_datajsonar', 'Jurisdiction')
    NodeMetadata = apps.get_model('django_datajsonar', 'NodeMetadata')
    for jurisdiction_model in Jurisdiction.objects.all():
        node_meta = NodeMetadata.objects.filter(jurisdiction=jurisdiction_model)
        if node_meta:
            argentinagobar_id = node_meta.first().argentinagobar_id
            jurisdiction_model.argentinagobar_id = argentinagobar_id


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0006_synchronizer_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=64)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('issued', models.DateField(blank=True, null=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project metadata',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('mbox', models.CharField(max_length=128, null=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('project_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.ProjectMetadata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spatial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spatial', models.CharField(max_length=64, null=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('project_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.ProjectMetadata')),
            ],
        ),
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='catalog_label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='types',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='datosgobar_url',
            new_name='url_datosgobar',
        ),
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='homepage_url',
            new_name='url_homepage',
        ),
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='json_url',
            new_name='url_json',
        ),
        migrations.RenameField(
            model_name='nodemetadata',
            old_name='xlsx_url',
            new_name='url_xlsx',
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='argentinagobar_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nodemetadata',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='language',
            name='project_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.ProjectMetadata'),
        ),
        migrations.RunPython(
            migrate_argentinagobar_ids,
            migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='nodemetadata',
            name='argentinagobar_id',
        ),

    ]
