# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0006_auto_20180523_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='readdatajsontask',
            name='indexing_mode',
            field=models.BooleanField(choices=[(True, 'Corrida completa'), (False, 'Corrida solo de metadatos')], default=True),
        ),
    ]
