# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-08 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0007_auto_20190507_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('issued', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project metadata',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('mbox', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='language',
            name='project_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.ProjectMetadata'),
        ),
    ]
