# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-14 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0007_auto_20190514_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='project_metadata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.ProjectMetadata'),
        ),
    ]
