# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_datajsonar', '0008_dataset_reviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'Metadatos enriquecidos', 'verbose_name_plural': 'Metadatos enriquecidos'},
        ),
        migrations.AddField(
            model_name='node',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
