# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0008_auto_20190508_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spatial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='publisher',
            name='project_metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.ProjectMetadata'),
        ),
    ]
