# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0009_auto_20190509_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatial',
            name='language',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='spatial',
            name='project_metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.ProjectMetadata'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='project_metadata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.ProjectMetadata'),
        ),
    ]
