# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0010_auto_20190517_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_ssl', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
