# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0010_auto_20190509_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spatial',
            old_name='language',
            new_name='spatial',
        ),
    ]
