# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0011_auto_20190509_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmetadata',
            name='modified',
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='language',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nodemetadata',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectmetadata',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spatial',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
