# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0011_dataset_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='error_msg',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataset',
            name='error_msg',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='distribution',
            name='error_msg',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='field',
            name='error_msg',
            field=models.TextField(default=''),
        ),
    ]
