# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0012_auto_20180831_1020'),
        ('django_datajsonar', '0012_stage_synchronizer'),
    ]

    operations = [
    ]
