# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0012_auto_20190509_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nodemetadata',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectmetadata',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spatial',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
    ]
