# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0012_auto_20190610_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.date(1970, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexingconfig',
            name='verify_ssl',
            field=models.BooleanField(default=False, verbose_name='Verify SSL'),
        ),
    ]
