# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0012_auto_20180831_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Tarea activa'), (False, 'Tarea inactiva')], default=False)),
                ('callable_str', models.CharField(max_length=100)),
                ('queue', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=200)),
                ('next_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='Synchronizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(choices=[(True, 'Corriendo procesos'), (False, 'En espera')], default=False)),
                ('actual_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='running_synchronizer', to='django_datajsonar.Stage')),
                ('start_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synchronizer', to='django_datajsonar.Stage')),
            ],
        ),
    ]
