# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0012_auto_20190610_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='newly_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indexingconfig',
            name='verify_ssl',
            field=models.BooleanField(default=False, verbose_name='Verify SSL'),
        ),
    ]
