# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0013_auto_20190827_1620'),
        ('django_datajsonar', '0013_auto_20190828_1643'),
    ]

    operations = [
    ]
