# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0013_stage_synchronizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='task',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
