# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0013_auto_20190509_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisdiction',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
    ]
