# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0014_auto_20180924_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchronizer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
