# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-04 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0014_merge_20190829_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='date_created',
        ),
        migrations.AddField(
            model_name='dataset',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
