# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0014_auto_20181011_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_title', models.CharField(max_length=100)),
                ('jurisdiction_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NodeMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_format', models.CharField(blank=True, choices=[('ckan', 'Portal CKAN'), ('xlsx', 'Cat\xe1logo XLSX'), ('json', 'Cat\xe1logo JSON')], max_length=20, null=True)),
                ('argentinagobar_id', models.CharField(blank=True, max_length=50, null=True)),
                ('catalog_label', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('central', 'Cat\xe1logo central'), ('no-central', 'Cat\xe1logo no central')], max_length=20, null=True)),
                ('types', models.CharField(blank=True, choices=[('andino', 'Andino'), ('excel', 'Excel'), ('ckan', 'CKAN'), ('other', 'Otros')], max_length=20, null=True)),
                ('json_url', models.URLField(blank=True, null=True)),
                ('xlsx_url', models.URLField(blank=True, null=True)),
                ('datosgobar_url', models.URLField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_datajsonar.Jurisdiction')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='node',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodemetadata',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Node'),
        ),
    ]
