# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0015_auto_20190107_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodemetadata',
            name='catalog_format',
        ),
        migrations.AddField(
            model_name='node',
            name='catalog_format',
            field=models.CharField(blank=True, choices=[('ckan', 'Portal CKAN'), ('xlsx', 'Catálogo XLSX'), ('json', 'Catálogo JSON')], max_length=20, null=True),
        ),
    ]
