# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0015_auto_20180925_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='name',
            field=models.CharField(default='stage', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
