# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-17 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0015_auto_20190904_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='timezone',
            field=models.CharField(default='America/Buenos_Aires', max_length=100),
        ),
    ]
