# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0016_auto_20190110_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizer',
            name='cron_string',
            field=models.CharField(default="0 0 * * *", max_length=64),
            preserve_default=False,
        ),
    ]
