# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-16 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0017_auto_20190923_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='validate_catalog_urls',
            field=models.BooleanField(default=True),
        ),
    ]
