# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0017_synchronizer_cron_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizer',
            name='last_time_ran',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 31, 14, 31, 6, 503777, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
