# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0018_node_validate_catalog_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='json_catalog_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='node',
            name='xlsx_catalog_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
