# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django_datajsonar.models.node
import django_datajsonar.storage.custom_catalog_storage


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0018_node_validate_catalog_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='json_catalog_file',
            field=models.FileField(blank=True, null=True, storage=django_datajsonar.storage.custom_catalog_storage.CustomCatalogStorage(), upload_to=django_datajsonar.models.node.catalog_file_path),
        ),
        migrations.AddField(
            model_name='node',
            name='xlsx_catalog_file',
            field=models.FileField(blank=True, null=True, storage=django_datajsonar.storage.custom_catalog_storage.CustomCatalogStorage(), upload_to=django_datajsonar.models.node.catalog_file_path),
        ),
    ]
