# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 15:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0018_synchronizer_last_time_ran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchronizer',
            name='cron_string',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
