# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-05 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0020_node_new_datasets_auto_indexable'),
        ('django_datajsonar', '0020_auto_20191031_1013'),
    ]

    operations = [
    ]
