 #-*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2026-06-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_datajsonar.models.utils
import minio_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0021_merge_20191105_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='data_file',
            field=models.FileField(blank=True, max_length=2000, storage=minio_storage.storage.MinioMediaStorage(), upload_to=django_datajsonar.models.utils.filepath),
        ),
    ]
