# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180503_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='value',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
