# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-04 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180503_1807'),
        ('api', '0003_metadata_value'),
    ]

    operations = [
    ]
