# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_dataset_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='error',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='periodicity',
        ),
        migrations.RemoveField(
            model_name='field',
            name='description',
        ),
        migrations.RemoveField(
            model_name='field',
            name='series_id',
        ),
        migrations.RemoveField(
            model_name='field',
            name='title',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
